### ISSUE TITLE
sys.exit()が機能しない件について

### ISSUE THREAD

**Issue by kota-shiokara** [kota-shiokara/processing-slackbot#1]
func.pyの関数、kill_process()において、print('process finished')は呼ばれているのにsys.exit()が機能していない
どうにかせねば

**Comment by t4t5u0** [comment]
https://github.com/lins05/slackbot/issues/131

sys._exit()を使うといいらしい

**Comment by kota-shiokara** [comment]
解決！解散！

**Comment by t4t5u0** [comment]
コードを修正するまでクローズしないほうがいいのでは

**Comment by kota-shiokara** [comment]
確かにそう。修正までこのissueオープンする。

**Comment by kota-shiokara** [comment]
修正完了、無事まーじしたので一旦寝る
