### ISSUE TITLE
cfg.py を生成させるのユーザからするとだるくね

### ISSUE THREAD

**Issue by t4t5u0** [kota-shiokara/processing-slackbot#17]
.py  でも .json  でもいいんだけど、とりあえず空のやつ置いておこ

**Comment by kota-shiokara** [comment]
空のやつ置いとくかあ、じゃあついでにslackbot_setthings.pyとsketchも置いとこ

**Comment by kota-shiokara** [comment]
何でユーザーに生成させたか思い出した
ファイル置いとくとignoreされない...

**Comment by kota-shiokara** [comment]
func.py内でsketchの絶対パス取得すればcfg.py自体は多分いらなくなるわ

**Comment by t4t5u0** [comment]
ファイル置いておくと gitignore  が反映されないのは
```
$ git rm --cache [file]
```
で外せる

```python
import pathlib
current_path =  pathlib.Path(__file__).resolve().parent / cfg.py
bot_path =  pathlib.Path(__file__).resolve().parents[1] 
```
みたいな感じで絶対パス作れる

みたいな雰囲気でいける

**Comment by kota-shiokara** [comment]
```$ git rm --cached [file]```は今日のICT演習で知った、使ってみるつもり

これfunc.pyはpluginsの中なので/sketch付けないといけないかなあ

**Comment by kota-shiokara** [comment]
結論：slackbot_settings.pyはユーザーに生成してもらう
sketchに関しては空のファイルでいいのでrun.pyの中に生成関数書こうかなとか考えた

**Comment by kota-shiokara** [comment]
・cfg.pyの廃止
・sketchディレクトリ、ファイルの自動生成
・slackbot_settings.pyはユーザーに生成してもらう
以上
